export type Language = "ru" | "en" | "kz";
export const copy = {
  ru: {
    skip: "Перейти к содержимому",
    pauseVideo: "Приостановить видео",
    playVideo: "Воспроизвести видео",
    videoAlt: "Ученики Semey New School в библиотеке",
    passwordMismatch: "Пароли должны совпадать",
    nav: ["О школе", "Наша миссия", "Библиотека", "Выпускникам", "Контакты"],
    portal: "Мой SNS",
    visit: "Посетить школу",
    menu: "Меню",
    close: "Закрыть",
    eyebrow: "SEMEY NEW SCHOOL · СЕМЕЙ, КАЗАХСТАН",
    hero: ["Большое будущее", "начинается здесь."],
    intro:
      "Место, где любопытство становится знанием, талант — уверенностью, а каждый ребёнок находит свой путь.",
    discover: "Откройте для себя SNS",
    film: "Жизнь в нашей школе",
    scroll: "ЛИСТАЙТЕ, ЧТОБЫ УЗНАТЬ БОЛЬШЕ",
    welcome: "ШКОЛА НОВОГО ПОКОЛЕНИЯ",
    welcomeTitle: "Больше, чем образование.",
    welcomeText:
      "Мы верим в потенциал каждого ребёнка. В Semey New School академические знания, творчество и забота о личности объединяются, чтобы подготовить детей к миру больших возможностей.",
    stats: [
      "Год основания",
      "Учебных кабинетов",
      "Языка обучения",
      "Школа полного дня",
    ],
    life: "ВОЗМОЖНОСТИ КАЖДЫЙ ДЕНЬ",
    lifeTitle: "Найти себя. Открыть мир.",
    cards: ["Учиться с интересом", "Расти вместе", "Пространство возможностей"],
    cardText: [
      "Знания, которые выходят за пределы учебника. Математика, языки, информатика и самостоятельные открытия.",
      "Учителя, которые вдохновляют. Сообщество, где ценят поддержку, уважение и индивидуальность.",
      "Современные пространства для учёбы, творчества и общения. Каждый день — новый шаг вперёд.",
    ],
    learn: "Узнать больше",
    invitation: "ВАШЕ ЗНАКОМСТВО С SNS",
    invitationTitle: "Почувствуйте нашу атмосферу.",
    invitationText:
      "Лучший способ узнать школу — увидеть её своими глазами. Свяжитесь с нами, чтобы договориться о визите и задать свои вопросы.",
    footer: "Раскрываем потенциал. Создаём будущее.",
    explore: "Узнайте о нас",
    touch: "Будем на связи",
    rights: "Все права защищены.",
    home: "Главная",
    subtitles: [
      "Познакомьтесь с пространством, в котором дети учатся, растут и открывают свои возможности.",
      "Образование, которое раскрывает потенциал и помогает уверенно смотреть в будущее.",
      "Знания всегда рядом. Найдите учебные материалы для своего следующего открытия.",
      "Новая глава начинается с уверенности в себе. Мы рядом на вашем пути.",
      "Давайте познакомимся. Будем рады ответить на ваши вопросы и встретить вас в школе.",
    ],
    search: "Название, автор или класс",
    all: "Все предметы",
    found: "Материалов",
    empty: "Ничего не найдено. Попробуйте другой запрос.",
    grade: "класс",
    author: "Автор",
    catalogNote:
      "Ознакомительный каталог. Для доступа к учебникам обратитесь в школьную библиотеку.",
    address: "Семей, улица Байсеитова, 5",
    phone: "Телефон",
    email: "Электронная почта",
    addressLabel: "Наш адрес",
    hours: "Понедельник — пятница · 08:00–17:00",
    directions: "Построить маршрут",
    call: "Позвонить в школу",
    write: "Написать письмо",
    next: "ВАШ СЛЕДУЮЩИЙ ШАГ",
    graduatesTitle: "Впереди — целый мир.",
    graduatesText:
      "Продолжайте учиться, задавать вопросы и пробовать новое. Школьная библиотека и поддержка нашей команды помогут вам подготовиться к следующему этапу.",
    steps: [
      "Подготовка к экзаменам",
      "Выбор своего пути",
      "Оставайтесь на связи",
    ],
    stepsText: [
      "Повторяйте материал и находите учебные ресурсы в нашей библиотеке.",
      "Обсудите ваши интересы и планы с учителями и семьёй.",
      "Свяжитесь со школой по вопросам документов и дальнейшего обучения.",
    ],
    login: "Добро пожаловать",
    loginText: "Войдите в личный кабинет, чтобы быть ближе к школьной жизни.",
    register: "Создать аккаунт",
    account: "ЛИЧНЫЙ КАБИНЕТ",
    password: "Пароль",
    confirm: "Подтвердите пароль",
    first: "Имя",
    last: "Фамилия",
    signIn: "Войти",
    noAccount: "Нет аккаунта?",
    hasAccount: "Уже есть аккаунт?",
    demo: "Сейчас доступен демонстрационный портал с примерами данных.",
    demoEnter: "Открыть демо-портал",
    unavailable:
      "Регистрация пока не подключена. Обратитесь в школу для получения аккаунта.",
    schedule: "Расписание",
    grades: "Оценки",
    profile: "Профиль",
    logout: "На сайт",
    student: "Ученический портал",
    demoLabel: "Демонстрационные данные",
    subject: "Предмет",
    time: "Время",
    teacher: "Учитель",
    room: "Кабинет",
    absence: "Пропуски",
    final: "Итог",
    dayNames: ["Понедельник", "Вторник", "Среда", "Четверг", "Пятница"],
    save: "Сохранить",
    edit: "Редактировать",
    saved: "Изменения сохранены в этом браузере.",
  },
  en: {
    skip: "Skip to content",
    pauseVideo: "Pause background video",
    playVideo: "Play background video",
    videoAlt: "Semey New School students in the library",
    passwordMismatch: "Passwords must match",
    nav: ["Our school", "Our mission", "Library", "Graduates", "Contact"],
    portal: "My SNS",
    visit: "Visit our school",
    menu: "Menu",
    close: "Close",
    eyebrow: "SEMEY NEW SCHOOL · SEMEY, KAZAKHSTAN",
    hero: ["A world of possibility", "starts here."],
    intro:
      "Where curiosity becomes knowledge, talent becomes confidence, and every child discovers their own path.",
    discover: "Discover SNS",
    film: "Life at our school",
    scroll: "SCROLL TO DISCOVER",
    welcome: "A SCHOOL FOR A NEW GENERATION",
    welcomeTitle: "More than an education.",
    welcomeText:
      "We believe in the potential of every child. At Semey New School, academic learning, creativity and personal care come together to prepare children for a world of possibilities.",
    stats: [
      "Founded",
      "Learning spaces",
      "Teaching languages",
      "Full-day school",
    ],
    life: "EVERYDAY POSSIBILITIES",
    lifeTitle: "Discover yourself. Explore your world.",
    cards: ["Inspired learning", "Growing together", "Room to discover"],
    cardText: [
      "Learning beyond the textbook. Mathematics, languages, technology and independent discoveries.",
      "Teachers who inspire. A community built on support, respect and individuality.",
      "Spaces for learning, creativity and connection. Every day is a new step forward.",
    ],
    learn: "Learn more",
    invitation: "YOUR INTRODUCTION TO SNS",
    invitationTitle: "Experience the difference.",
    invitationText:
      "The best way to get to know our school is to see it for yourself. Contact us to arrange a visit and ask your questions.",
    footer: "Unlocking potential. Shaping the future.",
    explore: "Explore SNS",
    touch: "Get in touch",
    rights: "All rights reserved.",
    home: "Home",
    subtitles: [
      "Discover a place where children learn, grow and find their possibilities.",
      "An education that unlocks potential and builds confidence for the future.",
      "Knowledge is always close. Find resources for your next discovery.",
      "Your next chapter starts with confidence. We are here for your journey.",
      "Let’s get to know each other. We look forward to your questions and your visit.",
    ],
    search: "Title, author or grade",
    all: "All subjects",
    found: "Resources",
    empty: "No results. Try a different search.",
    grade: "grade",
    author: "Author",
    catalogNote:
      "Preview catalogue. Contact the school library for access to textbooks.",
    address: "5 Baiseitova Street, Semey",
    phone: "Telephone",
    email: "Email",
    addressLabel: "Our address",
    hours: "Monday — Friday · 08:00–17:00",
    directions: "Get directions",
    call: "Call the school",
    write: "Send an email",
    next: "YOUR NEXT CHAPTER",
    graduatesTitle: "A whole world awaits.",
    graduatesText:
      "Keep learning, asking questions and trying new things. Our library and school team can help you prepare for your next step.",
    steps: ["Prepare for exams", "Find your direction", "Stay connected"],
    stepsText: [
      "Review your studies and find learning resources in our library.",
      "Discuss your interests and plans with your teachers and family.",
      "Contact the school for documents and further study enquiries.",
    ],
    login: "Welcome back",
    loginText: "Sign in to stay connected with school life.",
    register: "Create an account",
    account: "MY SNS",
    password: "Password",
    confirm: "Confirm password",
    first: "First name",
    last: "Last name",
    signIn: "Sign in",
    noAccount: "New here?",
    hasAccount: "Already have an account?",
    demo: "A demonstration portal with sample data is currently available.",
    demoEnter: "Explore the demo portal",
    unavailable:
      "Registration is not connected yet. Contact the school to request an account.",
    schedule: "Schedule",
    grades: "Grades",
    profile: "Profile",
    logout: "Back to website",
    student: "Student portal",
    demoLabel: "Demonstration data",
    subject: "Subject",
    time: "Time",
    teacher: "Teacher",
    room: "Room",
    absence: "Absences",
    final: "Final",
    dayNames: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    save: "Save",
    edit: "Edit",
    saved: "Changes saved in this browser.",
  },
  kz: {
    skip: "Мазмұнға өту",
    pauseVideo: "Видеоны кідірту",
    playVideo: "Видеоны ойнату",
    videoAlt: "Semey New School оқушылары кітапханада",
    passwordMismatch: "Құпиясөздер сәйкес болуы керек",
    nav: [
      "Мектеп туралы",
      "Біздің миссия",
      "Кітапхана",
      "Түлектерге",
      "Байланыс",
    ],
    portal: "Менің SNS",
    visit: "Мектепке келіңіз",
    menu: "Мәзір",
    close: "Жабу",
    eyebrow: "SEMEY NEW SCHOOL · СЕМЕЙ, ҚАЗАҚСТАН",
    hero: ["Үлкен болашақ", "осы жерден басталады."],
    intro:
      "Қызығушылық білімге, талант сенімділікке айналатын және әр бала өз жолын табатын орта.",
    discover: "SNS мектебімен танысыңыз",
    film: "Мектеп өмірі",
    scroll: "ТОЛЫҒЫРАҚ БІЛУ ҮШІН ТӨМЕН ТҮСІҢІЗ",
    welcome: "ЖАҢА БУЫН МЕКТЕБІ",
    welcomeTitle: "Білімнен де жоғары.",
    welcomeText:
      "Біз әр баланың әлеуетіне сенеміз. Semey New School мектебінде білім, шығармашылық және тұлғаға қамқорлық балаларды үлкен мүмкіндіктер әлеміне дайындайды.",
    stats: ["Құрылған жыл", "Оқу кабинеті", "Оқыту тілі", "Толық күн мектебі"],
    life: "КҮН САЙЫНҒЫ МҮМКІНДІКТЕР",
    lifeTitle: "Өзіңді тап. Әлемді таны.",
    cards: ["Қызығушылықпен оқу", "Бірге өсу", "Мүмкіндіктер кеңістігі"],
    cardText: [
      "Оқулықтан тыс білім. Математика, тілдер, информатика және өз бетінше ізденіс.",
      "Шабыт беретін ұстаздар. Қолдау, құрмет және даралық бағаланатын орта.",
      "Оқуға, шығармашылыққа және қарым-қатынасқа арналған кеңістіктер. Әр күн — жаңа қадам.",
    ],
    learn: "Толығырақ",
    invitation: "SNS МЕКТЕБІМЕН ТАНЫСУ",
    invitationTitle: "Біздің ортамызды сезініңіз.",
    invitationText:
      "Мектепті танудың ең жақсы жолы — оны өз көзіңізбен көру. Кездесу уақытын келісіп, сұрақтарыңызды қою үшін бізге хабарласыңыз.",
    footer: "Әлеуетті ашамыз. Болашақты құрамыз.",
    explore: "Біз туралы",
    touch: "Байланыста болайық",
    rights: "Барлық құқықтар қорғалған.",
    home: "Басты бет",
    subtitles: [
      "Балалар білім алып, өсіп, өз мүмкіндіктерін ашатын ортамен танысыңыз.",
      "Әлеуетті ашып, болашаққа сеніммен қарауға көмектесетін білім.",
      "Білім әрдайым қолжетімді. Келесі жаңалығыңызға қажетті оқу материалдарын табыңыз.",
      "Жаңа кезең өзіңізге сенуден басталады. Біз сіздің жолыңызда қолдау көрсетеміз.",
      "Танысайық. Сұрақтарыңызға жауап беріп, мектепте қарсы алуға қуаныштымыз.",
    ],
    search: "Атауы, авторы немесе сыныбы",
    all: "Барлық пәндер",
    found: "Материалдар",
    empty: "Ештеңе табылмады. Басқа сұрауды қолданып көріңіз.",
    grade: "сынып",
    author: "Автор",
    catalogNote:
      "Танысу каталогы. Оқулықтарға қол жеткізу үшін мектеп кітапханасына хабарласыңыз.",
    address: "Семей, Байсейітов көшесі, 5",
    phone: "Телефон",
    email: "Электрондық пошта",
    addressLabel: "Мекенжайымыз",
    hours: "Дүйсенбі — жұма · 08:00–17:00",
    directions: "Бағытты ашу",
    call: "Мектепке қоңырау шалу",
    write: "Хат жазу",
    next: "КЕЛЕСІ ҚАДАМЫҢЫЗ",
    graduatesTitle: "Алда — тұтас әлем.",
    graduatesText:
      "Білім алып, сұрақ қойып, жаңаны байқап көріңіз. Кітапханамыз бен мектеп ұжымы келесі кезеңге дайындалуға көмектеседі.",
    steps: ["Емтиханға дайындық", "Өз жолыңды таңдау", "Байланыста болыңыз"],
    stepsText: [
      "Материалдарды қайталап, кітапханамыздан оқу ресурстарын табыңыз.",
      "Қызығушылықтарыңыз бен жоспарларыңызды мұғалімдермен және отбасыңызбен талқылаңыз.",
      "Құжаттар және әрі қарай оқу мәселелері бойынша мектепке хабарласыңыз.",
    ],
    login: "Қош келдіңіз",
    loginText: "Мектеп өмірімен байланыста болу үшін жеке кабинетке кіріңіз.",
    register: "Аккаунт құру",
    account: "ЖЕКЕ КАБИНЕТ",
    password: "Құпиясөз",
    confirm: "Құпиясөзді растаңыз",
    first: "Аты",
    last: "Тегі",
    signIn: "Кіру",
    noAccount: "Аккаунтыңыз жоқ па?",
    hasAccount: "Аккаунтыңыз бар ма?",
    demo: "Қазір үлгі деректері бар демонстрациялық портал қолжетімді.",
    demoEnter: "Демо-порталды ашу",
    unavailable:
      "Тіркелу әзірге қосылмаған. Аккаунт алу үшін мектепке хабарласыңыз.",
    schedule: "Кесте",
    grades: "Бағалар",
    profile: "Профиль",
    logout: "Сайтқа оралу",
    student: "Оқушы порталы",
    demoLabel: "Демонстрациялық деректер",
    subject: "Пән",
    time: "Уақыт",
    teacher: "Мұғалім",
    room: "Кабинет",
    absence: "Қатыспау",
    final: "Қорытынды",
    dayNames: ["Дүйсенбі", "Сейсенбі", "Сәрсенбі", "Бейсенбі", "Жұма"],
    save: "Сақтау",
    edit: "Өңдеу",
    saved: "Өзгерістер осы браузерде сақталды.",
  },
};
export const publicPaths = [
  "/school-info",
  "/mission",
  "/e-library",
  "/for-graduates",
  "/contact-us",
];
